/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uygulama.denemesi;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cem
 */
public class LoanCalculator extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form KrediHesaplama
     */
    public LoanCalculator() {
        initComponents();
        jTable1.setModel(dtm);
        jLabel1.setText("Loan Amount");

        jLabel2.setText("Interest Rate (%)");

        jLabel3.setText("Term (Months)");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Kredi Miktarı");

        jLabel2.setText("Faiz Oranı");

        jLabel3.setText("Ödeme Süresi");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
            double loanAmount = Double.parseDouble(jTextField1.getText().replace(",", "."));
            // User inputs monthly interest rate as percent (e.g., 3.39)
            double monthlyInterestRate = Double.parseDouble(jTextField2.getText().replace(",", ".")) / 100.0;
            int months = Integer.parseInt(jTextField3.getText());

            if (loanAmount <= 0 || monthlyInterestRate < 0 || months <= 0) {
                JOptionPane.showMessageDialog(null, "Please enter positive values!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            final double KKDF_RATE = 0.15; // 15%
            final double BSMV_RATE = 0.15; // 15%
            double totalTaxRate = KKDF_RATE + BSMV_RATE; // Total tax rate

            // Effective monthly interest rate including taxes:
            double effectiveMonthlyRate = monthlyInterestRate * (1 + totalTaxRate);

            // Annuity equal installment formula
            double pow = Math.pow(1 + effectiveMonthlyRate, months);
            double monthlyPayment = loanAmount * (effectiveMonthlyRate * pow) / (pow - 1);
            monthlyPayment = Math.round(monthlyPayment * 100.0) / 100.0; // 2 decimals

            dtm.setRowCount(0);
            String[] headers = {"Installment", "Monthly Payment", "Principal", "Interest", "KKDF", "BSMV", "Remaining Balance"};
            dtm.setColumnIdentifiers(headers);

            double remainingPrincipal = loanAmount;
            double totalPrincipalPaid = 0;
            double totalInterestPaid = 0;
            double totalKKDFPaid = 0;
            double totalBSMVPaid = 0;
            double totalPayment = 0;

            for (int month = 1; month <= months; month++) {
                // Calculate interest on remaining principal
                double interest = remainingPrincipal * monthlyInterestRate;
                double kkdf = interest * KKDF_RATE;
                double bsmv = interest * BSMV_RATE;

                // Principal = monthly payment - interest - taxes
                double principal = monthlyPayment - (interest + kkdf + bsmv);
                remainingPrincipal -= principal;

                // Rounding
                interest = Math.round(interest * 100.0) / 100.0;
                kkdf = Math.round(kkdf * 100.0) / 100.0;
                bsmv = Math.round(bsmv * 100.0) / 100.0;
                principal = Math.round(principal * 100.0) / 100.0;
                remainingPrincipal = remainingPrincipal < 0 ? 0 : Math.round(remainingPrincipal * 100.0) / 100.0;

                totalPrincipalPaid += principal;
                totalInterestPaid += interest;
                totalKKDFPaid += kkdf;
                totalBSMVPaid += bsmv;
                totalPayment += monthlyPayment;

                dtm.addRow(new Object[]{
                    month + ".",
                    String.format("%,.2f TL", monthlyPayment),
                    String.format("%,.2f TL", principal),
                    String.format("%,.2f TL", interest),
                    String.format("%,.2f TL", kkdf),
                    String.format("%,.2f TL", bsmv),
                    String.format("%,.2f TL", remainingPrincipal)
                });
            }

            dtm.addRow(new Object[]{
                "Total",
                String.format("%,.2f TL", totalPayment),
                String.format("%,.2f TL", totalPrincipalPaid),
                String.format("%,.2f TL", totalInterestPaid),
                String.format("%,.2f TL", totalKKDFPaid),
                String.format("%,.2f TL", totalBSMVPaid),
                "-"
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
